### ISSUE TITLE
Color codes

### ISSUE THREAD

**Issue by acolytec3** [pfalcon/Chsmartbulb-led-bulb-speaker#1]
I used your code and found the hex values that control the light.  Try using these values in place of the ones you have in your script and you should get the colors you're looking for.  I've bolded the values in the string that control the brightness of each color channel.

sock.send(h("01fe0000538310000000000050**ff**0000")) #white 
sock.send(h('01fe0000538310000000**ff**0050000000')) #red
sock.send(h('01fe00005383100000**ff**000050000000')) #blue
sock.send(h('01fe000053831000**ff**00000050000000')) #green

**Comment by pfalcon** [comment]
@acolytec3 : Very cool, thanks for reaching back! I don't have access to the bulb now (and likely for few months more), but will try as soon as I can.

**Comment by eknoes** [comment]
Thanks @acolytec3, I have access to it and it works!

**Comment by pfalcon** [comment]
Sorry for the long lack of reply, I for a long time didn't have access to the bulb, then once I sit down to try, I figured I have problems with hardware connection of BT module in my laptop, so it didn't work. Well, it all finally converged, and I also confirm that it all works with info from @acolytec3. I dunno what's wrong with me that I missed it ;-).

I'm going to update this repo with this new info.

**Comment by pfalcon** [comment]
Ok, I updated the script/readme. Closing this then, thanks again!
